# Generated by Django 2.0.7 on 2021-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210417_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drinks', 'drinks'), ('entrees', 'entrees'), ('treats', 'treats'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
